### ISSUE TITLE
Request - Default to show All Runs on Load, not Summary

### ISSUE THREAD

**Issue by wilgf** [expertasolutions/AzDo.VstsDashboard#180]
I dont find the summary helpful, can you set the default to All Runs?  Or allow the user to select which default they want loaded each time?

**Comment by lturmel** [comment]
Hi @wilgf, 

Thanks you for requesting this improvement, yes, I will take not your proposition and include it in the december release.

**Comment by wilgf** [comment]
Thank you for your response! :)

This is a GREAT extension.  My whole team uses it.  But ya, they get
confused with the Summary.  They want to see every row and all the builds
for the current day when they load the dashboard.  The summary is rarely
used at all.  Great extension though!  I have no idea why MS did not
include a dashboard like this.  Great work! ")

- William

**Comment by lturmel** [comment]
Here a sneak peak for the next update... Pipeline stage support

![image](https://github.com/expertasolutions/AzDo.VstsDashboard/assets/46848645/e57c91f1-6cbe-4f6e-8d55-a47cca609f01)

**Comment by lturmel** [comment]
@wilgf  Thanks again for your comment... btw I just completed the change you made.
After quick review, I will add more user preferences persistency too.
Worst case, I plan this to be release around december 15th.

best regards,
